# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41dde2b4a72e11c4d911b83976e90d17f621bd67644fc3b86f09e2b761973eb536f97e3e2f1940d1c23cd590df5a2b7023ee10ab64a61c5ca055e44617542a61

test:
  secret_key_base: 239bed8e1fbfce373c36c2a340c0e045e52734a59796d401c16ea361e190c91d98ebd21fd23d8dde40a1fdd5905c54c8e22d434f2f9cdb1c24dcd92a46375407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
